name: BanTrial
version: ${project.version}
main: me.tomisanhues2.bantrial.Ban
author: Tomisanhues2
api-version: "1.13"
load: POSTWORLD
commands:
  ban:
    description: Ban a player
    aliases: tempban
    permission: bantrial.ban
  unban:
    description: Unban a player
    permission: bantrial.unban
  history:
    description: View a player's ban history
    permission: bantrial.history
  clearall:
    description: Clear all bans
    permission: bantrial.clearall

